env:
    SQLITE_VERSION: '3530200'
    PORTABLE_DIR: output/portable/Letos
    BRANCH_NAME: ${{ github.head_ref || github.ref_name }}
    SIGNPATH_CERT: 'release-signing'

name: Windows release build

on:
    workflow_dispatch:
        inputs:
          target:
            description: "Build target"
            type: choice
            options:
                - "all"
                - "x64"
                - "arm64"
            required: false
            default: "all"
          CODE_SIGN:
            description: 'Sign artifacts with SignPath'
            required: true
            type: boolean
            default: false
          use_ccache:
            description: 'Use ccache (for workflow debugging only!)'
            required: false
            type: boolean
          DEBUG:
            description: 'Enable workflow debug messages'
            required: false
            type: boolean
            default: false
          debug_ssh:
            description: "Open SSH tunnel at the end"
            type: boolean
            default: false
          debug_on_failure:
            description: "Open SSH tunnel if job fails"
            type: boolean
            default: false
    schedule:
        - cron: '0 2 * * 1' # run at 2 AM UTC every Monday

jobs:
    generate:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.set.outputs.matrix }}
        steps:
            - id: set
              run: |
                MATRIX_X64='{
                    "OS": "windows-2022",
                    "MSYSTEM": "CLANG64",
                    "CCACHE_KEY": "win64-release",
                    "SQLITE_ARCH": "x64",
                    "OUTPUT_FILE_ARCH": "x64"
                }'
                MATRIX_ARM64='{
                    "OS": "windows-11-arm",
                    "MSYSTEM": "CLANGARM64",
                    "CCACHE_KEY": "winarm64-release",
                    "SQLITE_ARCH": "arm64",
                    "OUTPUT_FILE_ARCH": "arm64"
                }'

                if [ "${{ inputs.target }}" = "x64" ]; then
                    matrix="[$MATRIX_X64]"
                elif [ "${{ inputs.target }}" = "arm64" ]; then
                    matrix="[$MATRIX_ARM64]"
                else
                    matrix="[$MATRIX_X64,$MATRIX_ARM64]"
                fi

                {
                    echo "matrix<<EOF"
                    echo "$matrix"
                    echo "EOF"
                } >> $GITHUB_OUTPUT

    build:
        needs: generate
        strategy:
            matrix:
                include: ${{ fromJson(needs.generate.outputs.matrix) }}

        runs-on: ${{ matrix.OS }}

        steps:
            - name: "[Prerequisites] Define portable dir path"
              shell: bash
              run: |
                ABSOLUTE_PORTABLE_DIR=$(realpath -m ${{ env.PORTABLE_DIR }})
                echo "ABSOLUTE_PORTABLE_DIR=$ABSOLUTE_PORTABLE_DIR" >> $GITHUB_ENV

            - name: "[Prerequisites] Define ISCC command"
              shell: bash
              run: |
                # Later the msys2 doesn't have it in the PATH
                ISCC=$(which iscc)
                echo "ISCC=$ISCC" >> $GITHUB_ENV

            - name: "[Prerequisites] Install MSYS2"
              uses: msys2/setup-msys2@v2
              with: 
                update: true
                msystem: ${{ matrix.MSYSTEM }}
                install: unzip
                pacboy: >-
                  cc-libs:p
                  qt6-base:p
                  qt6-declarative:p
                  qt6-imageformats:p
                  qt6-svg:p
                  zlib:p
                  7zip:p
                  cc:p
                  ccache:p
                  curl-winssl:p
                  make:p
                  ntldd:p
                  pkgconf:p
                  python:p
                  qt6-tools:p
                  tcl:p
                  cmake:p
                  ninja:p
                  tools:p
                  icu:p

            - name: "[Prerequisites] Clone GH scripts"
              uses: actions/checkout@v6
              with:
                repository: pawelsalawa/gh-action-scripts
                ref: main
                path: gh-scripts

            - name: "[Prerequisites] Setup GH scripts path"
              shell: msys2 {0}
              run: |
                mv gh-scripts ..
                cd ..
                echo "GH_SCRIPTS=$(pwd)/gh-scripts/scripts" >> $GITHUB_ENV
                echo "DEBUG=${{ inputs.DEBUG }}" >> $GITHUB_ENV

            - name: "[Prerequisites] Clone repo"
              uses: actions/checkout@v6
              with:
                ref: ${{ env.BRANCH_NAME }}

            - name: Determine Letos version
              shell: msys2 {0}
              run: |
                LETOS_VERSION=$(scripts/version_from_source.sh)
                echo "LETOS_VERSION=$LETOS_VERSION" >> $GITHUB_ENV
                echo "PACKAGE_VERSION=${LETOS_VERSION}-windows-${{ matrix.OUTPUT_FILE_ARCH }}" >> $GITHUB_ENV

            - name: "[Prerequisites] Prepare ccache"
              if: inputs.use_ccache || false
              uses: hendrikmuhs/ccache-action@v1.2
              with:
                key: ${{ matrix.CCACHE_KEY }}
                max-size: "24M"

            - name: "[Prerequisites] Configure ccache (or not ccache)"
              shell: msys2 {0}
              run: |
                if [ ${{ inputs.use_ccache || false }} = false ]; then
                    echo GCC_COMMAND="$(which clang.exe)"
                    echo GXX_COMMAND="$(which clang++.exe)"
                else
                    echo GCC_COMMAND="$CCACHE_COMMAND clang.exe"
                    echo GXX_COMMAND="$CCACHE_COMMAND clang++.exe"
                fi >> $GITHUB_ENV

            - name: "[Prerequisites] Install SQLite3 and extensions"
              shell: msys2 {0}
              run: |
                SQLITE_DOT_VERSION=$($GH_SCRIPTS/convert_int_ver.sh $SQLITE_VERSION)
                
                cd scripts/win32
                ./compile_sqlite_and_ext.sh \
                    https://github.com/pawelsalawa/sqlite3-letos/releases/download/v$SQLITE_DOT_VERSION/sqlite3-windows-${{ matrix.SQLITE_ARCH }}-$SQLITE_VERSION.zip \
                    https://github.com/pawelsalawa/sqlite3-letos/releases/download/v$SQLITE_DOT_VERSION/sqlite3-extensions-src-$SQLITE_VERSION.zip

            - name: Checkout private Icons8 repo
              uses: actions/checkout@v6
              with:
                repository: pawelsalawa/letos-icons8
                ref: main
                path: icons8
                token: ${{ secrets.LETOS_ICONS8_PAT }}
                persist-credentials: false

            - name: "[Building] Compile Letos and Plugins"
              shell: msys2 {0}
              run: |
                set -x
                cd scripts/win32
                ./compile.sh
                rm -rf ../../icons8

                find .

            - name: "[Assembling] Prepare portable distro (Resources)"
              shell: msys2 {0}
              run: |
                cp Letos/gui/img/letos.ico "$ABSOLUTE_PORTABLE_DIR"/appicon.ico
                cp Letos/gui/img/letos.svg "$ABSOLUTE_PORTABLE_DIR"/appicon.svg

            - name: "[Assembling] Assemble portable package"
              shell: msys2 {0}
              run: |
                cd $ABSOLUTE_PORTABLE_DIR/..
                7z a -r letos-$PACKAGE_VERSION.zip Letos
                ls -l

            - name: "[Assembling] Prepare portable artifact for uploading without signing"
              if: ${{ !inputs.CODE_SIGN }}
              shell: msys2 {0}
              run: |
                set -x
                mkdir unsigned
                cp output/portable/letos-${{ env.PACKAGE_VERSION }}.zip unsigned/
                cd unsigned
                7z x letos-${{ env.PACKAGE_VERSION }}.zip
                # echo "PORTABLE_DIR_FOR_INSTALLER=$(pwd)" >> $GITHUB_ENV
                echo "SIGNED_DIR=unsigned" >> $GITHUB_ENV

            - name: "[Code Signing] Prepare for code signing"
              if: ${{ inputs.CODE_SIGN }}
              shell: msys2 {0}
              run: |
                set -x
                mkdir signing signing/signed
                echo "SIGNED_DIR=signing/signed" >> $GITHUB_ENV

            - name: "[Code Signing] Prepare portable artifact for code signing"
              if: ${{ inputs.CODE_SIGN }}
              shell: msys2 {0}
              run: |
                set -x
                cp output/portable/letos-${{ env.PACKAGE_VERSION }}.zip signing/

            - name: "[Code Signing] Upload unsigned portable artifact"
              if: ${{ inputs.CODE_SIGN }}
              id: upload-unsigned-artifact-portable
              uses: actions/upload-artifact@v7
              with:
                name: unsigned-letos-${{ matrix.OUTPUT_FILE_ARCH }}-portable.zip
                path: signing/*.zip

            - name: "[Code Signing] Sign portable artifact"
              if: ${{ inputs.CODE_SIGN }}
              uses: signpath/github-action-submit-signing-request@v2
              with:
                api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
                organization-id: '78b5c545-92b8-4428-a8f9-31676f9553ba'
                project-slug: 'sqlitestudio'
                signing-policy-slug: '${{ env.SIGNPATH_CERT }}'
                github-artifact-id: '${{ steps.upload-unsigned-artifact-portable.outputs.artifact-id }}'
                github-token: '${{ secrets.SIGNPATH_GITHUB_TOKEN }}'
                wait-for-completion: true
                output-artifact-directory: '${{ env.SIGNED_DIR }}'

            - name: "[Code Signing] Unzip signed portable files to use for the installer"
              if: ${{ inputs.CODE_SIGN }}
              shell: msys2 {0}
              working-directory: ${{ env.SIGNED_DIR }}
              run: |
                set -x
                ls -l
                7z x letos-${{ env.PACKAGE_VERSION }}.zip
                ls -l
                # echo "PORTABLE_DIR_FOR_INSTALLER=$(pwd)" >> $GITHUB_ENV

            - name: "[Assembling] Create installer package"
              shell: msys2 {0}
              run: |
                $ISCC -DMyPortableDir=${{ env.SIGNED_DIR }}/Letos -DMyArch=${{ matrix.OUTPUT_FILE_ARCH }} InnoSetupScript.iss
                INSTALLER_FILE_NAME="Letos-${{ env.PACKAGE_VERSION }}-setup.exe"
                echo "INSTALLER_FILE_NAME=$INSTALLER_FILE_NAME" >> $GITHUB_ENV

            - name: "[Assembling] Prepare installer for uploading without signing"
              if: ${{ !inputs.CODE_SIGN }}
              shell: msys2 {0}
              run: |
                set -x
                cp output/$INSTALLER_FILE_NAME unsigned/

            - name: "[Code Signing] Prepare installer artifact for code signing"
              if: ${{ inputs.CODE_SIGN }}
              shell: msys2 {0}
              run: |
                set -x
                cp output/$INSTALLER_FILE_NAME signing/

            - name: "[Code Signing] Upload unsigned installer artifact"
              if: ${{ inputs.CODE_SIGN }}
              id: upload-unsigned-artifact-installer
              uses: actions/upload-artifact@v7
              with:
                name: unsigned-letos-${{ matrix.OUTPUT_FILE_ARCH }}-installer.zip
                path: signing/*.exe

            - name: "[Code Signing] Sign installer artifact"
              if: ${{ inputs.CODE_SIGN }}
              uses: signpath/github-action-submit-signing-request@v2
              with:
                api-token: '${{ secrets.SIGNPATH_API_TOKEN }}'
                organization-id: '78b5c545-92b8-4428-a8f9-31676f9553ba'
                project-slug: 'sqlitestudio'
                signing-policy-slug: '${{ env.SIGNPATH_CERT }}'
                github-artifact-id: '${{ steps.upload-unsigned-artifact-installer.outputs.artifact-id }}'
                github-token: '${{ secrets.SIGNPATH_GITHUB_TOKEN }}'
                wait-for-completion: true
                output-artifact-directory: '${{ env.SIGNED_DIR }}'

            - name: "[Assembling] SHA256 checksums"
              shell: msys2 {0}
              working-directory: ${{ env.SIGNED_DIR }}
              run: |
                sha256sum letos-${{ env.PACKAGE_VERSION }}.zip
                sha256sum $INSTALLER_FILE_NAME

            - name: Upload package artifact
              uses: actions/upload-artifact@v7
              with:
                name: letos-${{ env.PACKAGE_VERSION }}.zip
                path: ${{ env.SIGNED_DIR }}/letos-${{ env.PACKAGE_VERSION }}.zip

            - name: Upload installer artifact
              uses: actions/upload-artifact@v7
              with:
                name: Letos-${{ env.PACKAGE_VERSION }}-installer.exe
                path: ${{ env.SIGNED_DIR }}/${{ env.INSTALLER_FILE_NAME }}

            - name: Cleanup before running SSH
              if: >
                ${{
                    github.repository_owner == 'pawelsalawa'
                    && (inputs.debug_ssh || (failure() && inputs.debug_on_failure))
                }}
              shell: msys2 {0}
              run: |
                rm -rf icons8

            - name: Setup debugging SSH
              if: >
                ${{
                    github.repository_owner == 'pawelsalawa'
                    && (inputs.debug_ssh || (failure() && inputs.debug_on_failure))
                }}
              uses: owenthereal/action-upterm@v1
              with:
                wait-timeout-minutes: 10
