<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="nl" sourcelanguage="en">
<context>
    <name>HtmlExport</name>
    <message>
        <location filename="../htmlexport.cpp" line="45"/>
        <source>SQL query results</source>
        <translation>SQL-queryresultaten</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="54"/>
        <source>Query:</source>
        <translation>Query:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="94"/>
        <location filename="../htmlexport.cpp" line="188"/>
        <source>no type</source>
        <translation>geen type</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="125"/>
        <source>Exported table: %1</source>
        <translation>Geëxporteerde tabel: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="136"/>
        <source>Exported view: %1</source>
        <translation>Geëxporteerde view: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="157"/>
        <location filename="../htmlexport.cpp" line="280"/>
        <source>Table: %1</source>
        <translation>Tabel: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="283"/>
        <source>virtual</source>
        <translation>virtueel</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="335"/>
        <source>Exported database: %1</source>
        <translation>Geëxporteerde database: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="351"/>
        <source>Index: %1</source>
        <translation>Index: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="357"/>
        <source>For table:</source>
        <translation>Voor tabel:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="364"/>
        <source>Unique:</source>
        <translation>Uniek:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>Yes</source>
        <translation>Ja</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>No</source>
        <translation>Nee</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="371"/>
        <source>Column</source>
        <translation>Kolom</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="372"/>
        <source>Collating</source>
        <translation>Collatie</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="373"/>
        <source>Sort order</source>
        <translation>Sorteervolgorde</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="407"/>
        <source>Trigger: %1</source>
        <translation>Trigger: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="413"/>
        <source>Activated:</source>
        <translation>Geactiveerd:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="421"/>
        <source>Action:</source>
        <translation>Actie:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="428"/>
        <source>On view:</source>
        <translation>Op view:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="430"/>
        <source>On table:</source>
        <translation>Op tabel:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="441"/>
        <source>Activate condition:</source>
        <translation>Activeringsvoorwaarde:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="448"/>
        <source>Code executed:</source>
        <translation>Uitgevoerde code:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="486"/>
        <source>View: %1</source>
        <translation>Weergave: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="565"/>
        <source>Document generated by Letos v%1 on %2</source>
        <translation>Document gegenereerd door Letos v%1 op %2</translation>
    </message>
</context>
<context>
    <name>HtmlExportConfig</name>
    <message>
        <location filename="../htmlexport.ui" line="136"/>
        <source>Maximum number of characters per cell:</source>
        <translation>Maximaal aantal tekens per cel:</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="182"/>
        <source>Include data types in first row</source>
        <translation>Gegevenstypen opnemen in de eerste rij</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="143"/>
        <source>Column names as first row</source>
        <translation>Kolomnamen als eerste rij</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="126"/>
        <source>Row numbers as first column</source>
        <translation>Rijnummers als eerste kolom</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="91"/>
        <source>Output format</source>
        <translation>Uitvoerformaat</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="20"/>
        <source>Custom header</source>
        <translation>Aangepaste koptekst</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="26"/>
        <source>No custom header</source>
        <translation>Geen aangepaste koptekst</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="39"/>
        <source>Define custom header content</source>
        <translation>Inhoud van aangepaste koptekst definiëren</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="52"/>
        <location filename="../htmlexport.ui" line="224"/>
        <source>HTML content</source>
        <translation>HTML-inhoud</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="62"/>
        <source>Define custom header file</source>
        <translation>Aangepast koptekstbestand definiëren</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="78"/>
        <source>Choose file for the header</source>
        <translation>Bestand voor de koptekst kiezen</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="81"/>
        <location filename="../htmlexport.ui" line="253"/>
        <source>HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</source>
        <translation>HTML-bestanden (*.htm, *.html);;Tekstbestanden (*.txt);;Alle bestanden (*)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="97"/>
        <source>Format document (new lines, indentation)</source>
        <translation>Document opmaken (nieuwe regels, inspringing)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="110"/>
        <source>Compress (everything in one line)</source>
        <translation>Comprimeren (alles op één regel)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="153"/>
        <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
        <translation>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="156"/>
        <source>Don&apos;t escape HTML characters</source>
        <translation>HTML-tekens niet escapen</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="192"/>
        <source>Custom footer</source>
        <translation>Aangepaste voettekst</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="198"/>
        <source>No custom footer</source>
        <translation>Geen aangepaste voettekst</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="211"/>
        <source>Define custom footer content</source>
        <translation>Inhoud van aangepaste voettekst definiëren</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="234"/>
        <source>Define custom footer file</source>
        <translation>Aangepast voettekstbestand definiëren</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="250"/>
        <source>Choose file for the footer</source>
        <translation>Bestand voor de voettekst kiezen</translation>
    </message>
</context>
</TS>
