<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="cs" sourcelanguage="en">
<context>
    <name>HtmlExport</name>
    <message>
        <location filename="../htmlexport.cpp" line="45"/>
        <source>SQL query results</source>
        <translation>Výsledky SQL dotazu</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="54"/>
        <source>Query:</source>
        <translation>Dotaz:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="94"/>
        <location filename="../htmlexport.cpp" line="188"/>
        <source>no type</source>
        <translation>bez typu</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="125"/>
        <source>Exported table: %1</source>
        <translation>Exportovaná tabulka: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="136"/>
        <source>Exported view: %1</source>
        <translation>Exportovaný pohled: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="157"/>
        <location filename="../htmlexport.cpp" line="280"/>
        <source>Table: %1</source>
        <translation>Tabulka: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="283"/>
        <source>virtual</source>
        <translation>virtuální</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="335"/>
        <source>Exported database: %1</source>
        <translation>Exportovaná databáze: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="351"/>
        <source>Index: %1</source>
        <translation>Index: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="357"/>
        <source>For table:</source>
        <translation>Pro tabulku:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="364"/>
        <source>Unique:</source>
        <translation>Jedinečný:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>Yes</source>
        <translation>Ano</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>No</source>
        <translation>Ne</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="371"/>
        <source>Column</source>
        <translation>Sloupec</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="372"/>
        <source>Collating</source>
        <translation>Kolace</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="373"/>
        <source>Sort order</source>
        <translation>Pořadí řazení</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="407"/>
        <source>Trigger: %1</source>
        <translation>Trigger: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="413"/>
        <source>Activated:</source>
        <translation>Aktivováno:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="421"/>
        <source>Action:</source>
        <translation>Akce:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="428"/>
        <source>On view:</source>
        <translation>Na pohledu:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="430"/>
        <source>On table:</source>
        <translation>Na tabulce:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="441"/>
        <source>Activate condition:</source>
        <translation>Podmínka aktivace:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="448"/>
        <source>Code executed:</source>
        <translation>Spuštěný kód:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="486"/>
        <source>View: %1</source>
        <translation>Pohled: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="565"/>
        <source>Document generated by Letos v%1 on %2</source>
        <translation>Dokument vygenerován aplikací Letos v%1 dne %2</translation>
    </message>
</context>
<context>
    <name>HtmlExportConfig</name>
    <message>
        <location filename="../htmlexport.ui" line="136"/>
        <source>Maximum number of characters per cell:</source>
        <translation>Maximální počet znaků v buňce:</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="182"/>
        <source>Include data types in first row</source>
        <translation>Zahrnout datové typy do prvního řádku</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="143"/>
        <source>Column names as first row</source>
        <translation>Názvy sloupců jako první řádek</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="126"/>
        <source>Row numbers as first column</source>
        <translation>Čísla řádků jako první sloupec</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="91"/>
        <source>Output format</source>
        <translation>Výstupní formát</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="20"/>
        <source>Custom header</source>
        <translation>Vlastní záhlaví</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="26"/>
        <source>No custom header</source>
        <translation>Bez vlastního záhlaví</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="39"/>
        <source>Define custom header content</source>
        <translation>Definovat obsah vlastního záhlaví</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="52"/>
        <location filename="../htmlexport.ui" line="224"/>
        <source>HTML content</source>
        <translation>Obsah HTML</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="62"/>
        <source>Define custom header file</source>
        <translation>Definovat soubor vlastního záhlaví</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="78"/>
        <source>Choose file for the header</source>
        <translation>Vybrat soubor pro záhlaví</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="81"/>
        <location filename="../htmlexport.ui" line="253"/>
        <source>HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</source>
        <translation>Soubory HTML (*.htm, *.html);;Textové soubory (*.txt);;Všechny soubory (*)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="97"/>
        <source>Format document (new lines, indentation)</source>
        <translation>Formátovat dokument (nové řádky, odsazení)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="110"/>
        <source>Compress (everything in one line)</source>
        <translation>Komprimovat (vše na jednom řádku)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="153"/>
        <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
        <translation>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="156"/>
        <source>Don&apos;t escape HTML characters</source>
        <translation>Neescapovat znaky HTML</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="192"/>
        <source>Custom footer</source>
        <translation>Vlastní zápatí</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="198"/>
        <source>No custom footer</source>
        <translation>Bez vlastního zápatí</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="211"/>
        <source>Define custom footer content</source>
        <translation>Definovat obsah vlastního zápatí</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="234"/>
        <source>Define custom footer file</source>
        <translation>Definovat soubor vlastního zápatí</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="250"/>
        <source>Choose file for the footer</source>
        <translation>Vybrat soubor pro zápatí</translation>
    </message>
</context>
</TS>
