<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE TS>
<TS version="2.1" language="uk" sourcelanguage="en">
<context>
    <name>HtmlExport</name>
    <message>
        <location filename="../htmlexport.cpp" line="45"/>
        <source>SQL query results</source>
        <translation>Результати SQL-запиту</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="54"/>
        <source>Query:</source>
        <translation>Запит:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="94"/>
        <location filename="../htmlexport.cpp" line="188"/>
        <source>no type</source>
        <translation>без типу</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="125"/>
        <source>Exported table: %1</source>
        <translation>Експортована таблиця: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="136"/>
        <source>Exported view: %1</source>
        <translation>Експортоване подання: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="157"/>
        <location filename="../htmlexport.cpp" line="280"/>
        <source>Table: %1</source>
        <translation>Таблиця: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="283"/>
        <source>virtual</source>
        <translation>віртуальна</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="335"/>
        <source>Exported database: %1</source>
        <translation>Експортована база даних: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="351"/>
        <source>Index: %1</source>
        <translation>Індекс: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="357"/>
        <source>For table:</source>
        <translation>Для таблиці:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="364"/>
        <source>Unique:</source>
        <translation>Унікальний:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>Yes</source>
        <translation>Так</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="365"/>
        <source>No</source>
        <translation>Ні</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="371"/>
        <source>Column</source>
        <translation>Стовпець</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="372"/>
        <source>Collating</source>
        <translation>Зіставлення</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="373"/>
        <source>Sort order</source>
        <translation>Порядок сортування</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="407"/>
        <source>Trigger: %1</source>
        <translation>Тригер: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="413"/>
        <source>Activated:</source>
        <translation>Активовано:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="421"/>
        <source>Action:</source>
        <translation>Дія:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="428"/>
        <source>On view:</source>
        <translation>У поданні:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="430"/>
        <source>On table:</source>
        <translation>У таблиці:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="441"/>
        <source>Activate condition:</source>
        <translation>Умова активації:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="448"/>
        <source>Code executed:</source>
        <translation>Виконаний код:</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="486"/>
        <source>View: %1</source>
        <translation>Подання: %1</translation>
    </message>
    <message>
        <location filename="../htmlexport.cpp" line="565"/>
        <source>Document generated by Letos v%1 on %2</source>
        <translation>Документ створено Letos v%1 %2</translation>
    </message>
</context>
<context>
    <name>HtmlExportConfig</name>
    <message>
        <location filename="../htmlexport.ui" line="136"/>
        <source>Maximum number of characters per cell:</source>
        <translation>Максимальна кількість символів у комірці:</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="182"/>
        <source>Include data types in first row</source>
        <translation>Додати типи даних у перший рядок</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="143"/>
        <source>Column names as first row</source>
        <translation>Назви стовпців як перший рядок</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="126"/>
        <source>Row numbers as first column</source>
        <translation>Номери рядків як перший стовпець</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="91"/>
        <source>Output format</source>
        <translation>Формат виводу</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="20"/>
        <source>Custom header</source>
        <translation>Користувацький верхній колонтитул</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="26"/>
        <source>No custom header</source>
        <translation>Без користувацького верхнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="39"/>
        <source>Define custom header content</source>
        <translation>Визначити вміст користувацького верхнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="52"/>
        <location filename="../htmlexport.ui" line="224"/>
        <source>HTML content</source>
        <translation>HTML-вміст</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="62"/>
        <source>Define custom header file</source>
        <translation>Визначити файл користувацького верхнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="78"/>
        <source>Choose file for the header</source>
        <translation>Виберіть файл для верхнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="81"/>
        <location filename="../htmlexport.ui" line="253"/>
        <source>HTML files (*.htm, *.html);;Text files (*.txt);;All files (*)</source>
        <translation>HTML-файли (*.htm, *.html);;Текстові файли (*.txt);;Усі файли (*)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="97"/>
        <source>Format document (new lines, indentation)</source>
        <translation>Форматувати документ (нові рядки, відступи)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="110"/>
        <source>Compress (everything in one line)</source>
        <translation>Стиснути (усе в один рядок)</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="153"/>
        <source>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp;amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</source>
        <translation>&lt;p&gt;When enabled, HTML characters such as &amp;lt;, &amp;gt; and &amp; are not escaped in exported values. This allows you for example to export hyper-link enabled documents, but it also may result in incorrect HTML document (unmatched pairs of &amp;lt; and &amp;gt; characters). Be warned.&lt;/p&gt;</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="156"/>
        <source>Don&apos;t escape HTML characters</source>
        <translation>Не екранувати HTML-символи</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="192"/>
        <source>Custom footer</source>
        <translation>Користувацький нижній колонтитул</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="198"/>
        <source>No custom footer</source>
        <translation>Без користувацького нижнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="211"/>
        <source>Define custom footer content</source>
        <translation>Визначити вміст користувацького нижнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="234"/>
        <source>Define custom footer file</source>
        <translation>Визначити файл користувацького нижнього колонтитула</translation>
    </message>
    <message>
        <location filename="../htmlexport.ui" line="250"/>
        <source>Choose file for the footer</source>
        <translation>Виберіть файл для нижнього колонтитула</translation>
    </message>
</context>
</TS>
